name: "Hello world workflow"


#Controls when the action will run. triggers the workflow on push to master or any production branch
on:
    push:
        branches:
            - main
            - production
jobs:
    hello_world:
        runs-on: ubuntu-latest
#define a list using an -
        steps:
            - name: "Print hello world"
              run: echo "Hello world"   
            - name: "Print current date"
              run: date   
