name: "Multi event pipeline/workflow"
on:
    #Event here is push to master branch
    push:
    pull_request: 
        branches:
            - main
            - test
    workflow_dispatch:

jobs: 
    on-push: #job1
        if: github.event_name == 'push' #condition to only execute this task if push is being done
        runs-on: ubuntu-latest
        steps: #steps to be executed in the job
            - name: "Running on master/test push"
              run: echo "Running on master/test push"
    
    on-pull-request: #job2
        if: github.event_name == 'pull_request'
        runs-on: ubuntu-latest
        steps:
            - name: "Running on main pull request"
              run: echo "Running on pull request"    
